import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

/**
 * 同步插件文件到 release 文件夹
 * 每次构建后将 main.js, manifest.json, styles.css 复制到 release/
 */
function syncToRelease() {
	const releaseDir = 'release';

	// 确保 release 目录存在
	if (!fs.existsSync(releaseDir)) {
		fs.mkdirSync(releaseDir, { recursive: true });
	}

	const files = ['main.js', 'manifest.json', 'styles.css'];

	for (const file of files) {
		const srcPath = file;
		const destPath = path.join(releaseDir, file);

		if (fs.existsSync(srcPath)) {
			fs.copyFileSync(srcPath, destPath);
			console.log(`Synced: ${srcPath} -> ${destPath}`);
		}
	}
}

console.log(`Building: main.ts -> main.js`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	// 同步到 release 文件夹
	syncToRelease();
	process.exit(0);
} else {
	await context.watch();
}
