import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const version = process.argv[3] || 'v1'; // v1, v2, or v3

// 根据版本选择入口文件和输出路径
let entryPoint;
let outfile;

switch (version) {
	case 'v2':
		entryPoint = 'v2/main.ts';
		outfile = 'v2/main.js';
		break;
	case 'v3':
		entryPoint = 'v3/main.ts';
		outfile = 'v3/main.js';
		break;
	default:
		entryPoint = 'v1/main.ts';
		outfile = 'v1/main.js';
}

console.log(`Building ${version}: ${entryPoint} -> ${outfile}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: outfile,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
